"""

/***************************************************************************
 LineProfile
                                 A QGIS plugin
 Create line profiles from attribute table in vector layer and color band of raster layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-10-30
        git sha              : $Format:%H$
        copyright            : (C) 2020 by WiscSIMS (Kouki Kitajima)
        email                : kitajima@wisc.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import os.path
import re
import json
import math
import csv
from itertools import combinations
from functools import reduce

from qgis.PyQt.QtGui import QIcon

from qgis.PyQt.QtCore import (
    QSettings,
    QTranslator,
    QCoreApplication,
    QVariant,
    QTimer,
)
from qgis.PyQt.QtWidgets import (
    QAction,
    QFileDialog,
    QInputDialog,
    QMenu,
    QMessageBox,
)

from qgis.core import (
    Qgis,
    QgsProject,
    QgsVectorLayer,
    QgsField,
    QgsFeature,
    QgsGeometry,
    QgsVectorFileWriter,
    QgsPoint,
    QgsPointXY,
    QgsMessageLog,
)

# Initialize Qt resources from file resources.py
from .resources import *

# Import tools
from .tools.plottingTool import PlottingTool
from .tools.profileLineTool import ProfileLineTool
from .tools.dataProcessingTool import DataProcessingTool
from .tools.myTableViewModel import MyTableViewModel
from .tools.profilePlotConverter import ProfilePlotConverter
from .tools.peakDetectionTool import (
    PROMINENCE_ABSOLUTE,
    PROMINENCE_LOCAL_MAD,
    PROMINENCE_LOCAL_RANGE,
    PROMINENCE_LOCAL_SD,
    PeakDetectionTool,
)
from .tools.featurePointStore import FeaturePointStore
from .tools.dependencyManager import SciPyDependencyManager
from .tools.profileVisibility import distance_in_ranges, visible_profile_ranges
from .tools.detectionScope import (
    SCOPE_CURRENT_MAP_EXTENT,
    SCOPE_FULL_PROFILE,
    SCOPE_SELECTED_RANGES,
    detect_in_ranges,
    full_profile_ranges,
)
from .tools.rangeUtils import format_ranges, merge_ranges, parse_ranges
from .tools.featurePointIO import (
    export_feature_points as export_feature_point_file,
    map_imported_points,
    parse_import_rows,
    read_delimited_rows,
)
from .tools.profileProcessing import (
    SMOOTHING_GAUSSIAN,
    SMOOTHING_SAVGOL,
    process_profile,
    processed_data,
    smoothing_mode,
    smoothing_signature,
)

# Import UI (dock and dialogs)
from .ui.dockWidget import DockWidget
from .ui.lpExportDialog import LPExportDialog
from .ui.lpImportDialog import LPImportDialog
from .ui.lpConfigPlotDialog import LPConfigPlotDialog


class LineProfile:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value("locale/userLocale")[0:2]
        locale_path = os.path.join(self.plugin_dir, "i18n", "LineProfile_{}.qm".format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr("&WiscSIMS")
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar("LineProfile")
        self.toolbar.setObjectName("LineProfile")

        self.pluginIsActive = False
        # self.dockwidget = None
        # self.DockWidget = None

        # self.dock = None
        self.dockOpened = False
        self.canvas = self.iface.mapCanvas()
        self.originalMapTool = self.canvas.mapTool()

        self.closingFlag = False
        self.debugFlag = False

        self.model = MyTableViewModel()

        self.timer_pixel_size_spin_box = QTimer()
        self.timer_pixel_size_spin_box.setSingleShot(True)

        self.timer_resize_widget = QTimer()
        self.timer_resize_widget.setSingleShot(True)

        self.timer_map_extent = QTimer()
        self.timer_map_extent.setSingleShot(True)
        self.timer_map_extent.setInterval(200)

        self.n_profile_lines = 2
        self.pLines = []
        self.plotData = []
        self.current_visible_profile_ranges = None
        self.detection_ranges = {index: [] for index in range(self.n_profile_lines)}
        self.pending_detection_range_start = None

        # instancialize tools
        self.profileLineTool = ProfileLineTool(self.canvas)
        self.plotTool = PlottingTool(self.model, self.drawTracer, self.handle_feature_plot_click)
        self.dpTool = DataProcessingTool(self.n_profile_lines)
        self.ppc = ProfilePlotConverter()
        self.peakDetectionTool = PeakDetectionTool()
        self.featurePointStore = FeaturePointStore()
        self.scipyDependencyManager = SciPyDependencyManager()
        self.feature_data_signatures = {}
        self.point_menu_actions = []

    def log_message(self, message, level=Qgis.Warning):
        QgsMessageLog.logMessage(str(message), "Line Profile", level)

    # noinspection PyMethodMayBeStatic

    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate("LineProfile", message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ":/plugins/line_profile/img/icon.png"
        self.line_profile_action = self.add_action(
            icon_path,
            text=self.tr("Line Profile"),
            callback=self.run,
            whats_this=self.tr("Plot Line Profiles"),
            parent=self.iface.mainWindow(),
        )
        self.line_profile_action.setCheckable(True)

    # --------------------------------------------------------------------------
    @staticmethod
    def _safe_disconnect(signal, callback):
        try:
            signal.disconnect(callback)
        except (AttributeError, RuntimeError, TypeError):
            pass

    def stop_plugin_timers(self):
        """Prevent callbacks owned by this instance from running after close."""
        for name in (
            "timer_pixel_size_spin_box",
            "timer_resize_widget",
            "timer_map_extent",
        ):
            timer = getattr(self, name, None)
            if timer is not None:
                try:
                    timer.stop()
                except RuntimeError:
                    pass

    def disconnect_map_tool(self, restore_previous=True):
        """Detach this instance's map tool without disturbing a newer tool."""
        self._safe_disconnect(self.canvas.mapToolSet, self.mapToolChanged)
        try:
            current_tool = self.canvas.mapTool()
        except RuntimeError:
            return
        if current_tool is not self.profileLineTool:
            return

        previous_tool = getattr(self, "prev_tool", None)
        if previous_tool is self.profileLineTool:
            previous_tool = None
        if previous_tool is None:
            previous_tool = getattr(self, "originalMapTool", None)
        if previous_tool is self.profileLineTool:
            previous_tool = None

        if restore_previous and previous_tool is not None:
            try:
                self.canvas.setMapTool(previous_tool)
                return
            except RuntimeError:
                pass
        try:
            self.canvas.unsetMapTool(self.profileLineTool)
        except RuntimeError:
            pass

    def cleanup_canvas_items(self, destroy=False):
        """Hide reusable graphics or permanently remove all canvas objects."""
        try:
            if destroy:
                self.profileLineTool.remove_all_canvas_items()
            else:
                self.profileLineTool.hide_profile_line()
        except (AttributeError, RuntimeError) as error:
            self.log_message("Profile graphics cleanup failed: {}".format(error))

    def cleanup_plot_widget(self):
        try:
            self.plotTool.releasePlotWidget()
        except (AttributeError, RuntimeError):
            pass

    def remove_dock(self):
        """Remove and destroy the dock owned by the QGIS main window."""
        dock = getattr(self, "dock", None)
        if dock is None:
            return

        self.dock = None
        self.dockOpened = False
        try:
            self._safe_disconnect(dock.closingPlugin, self.onClosePlugin)
        except RuntimeError:
            pass
        try:
            dock.disconnectTable()
        except (AttributeError, RuntimeError, TypeError):
            pass
        try:
            self.iface.removeDockWidget(dock)
        except (AttributeError, RuntimeError, TypeError):
            pass
        try:
            dock.setParent(None)
        except RuntimeError:
            pass
        try:
            dock.close()
        except RuntimeError:
            pass
        try:
            dock.deleteLater()
        except RuntimeError:
            pass

    def remove_actions(self):
        """Remove every action from the same menu and toolbar used at setup."""
        for action in list(self.actions):
            try:
                self.iface.removePluginMenu(self.menu, action)
            except (AttributeError, RuntimeError, TypeError):
                pass
            try:
                self.iface.removeToolBarIcon(action)
            except (AttributeError, RuntimeError, TypeError):
                pass
            try:
                action.setEnabled(False)
                action.triggered.disconnect()
                action.setParent(None)
            except (AttributeError, RuntimeError, TypeError):
                pass
            try:
                action.deleteLater()
            except (AttributeError, RuntimeError):
                pass
        self.actions = []
        self.line_profile_action = None

    def remove_toolbar(self):
        """Remove the QMainWindow-owned toolbar widget, not only its reference."""
        toolbar = getattr(self, "toolbar", None)
        if toolbar is None:
            return
        self.toolbar = None
        try:
            toolbar.clear()
        except RuntimeError:
            pass
        try:
            self.iface.mainWindow().removeToolBar(toolbar)
        except (AttributeError, RuntimeError, TypeError):
            pass
        try:
            toolbar.setParent(None)
        except RuntimeError:
            pass
        try:
            toolbar.deleteLater()
        except RuntimeError:
            pass

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""
        dock = getattr(self, "dock", None)
        self.pluginIsActive = False
        self.stop_plugin_timers()
        self.disconnectTools()
        if dock is not None:
            self.disconnectDock()
            self._safe_disconnect(dock.closingPlugin, self.onClosePlugin)
        self.disconnect_map_tool(restore_previous=True)
        self.cleanup_canvas_items(destroy=False)
        self.cleanup_plot_widget()
        action = getattr(self, "line_profile_action", None)
        if action is not None:
            try:
                action.setChecked(False)
            except RuntimeError:
                pass
        self.dock = None
        self.dockOpened = False

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        self.pluginIsActive = False
        self.stop_plugin_timers()
        self.disconnectTools()
        if getattr(self, "dock", None) is not None:
            self.disconnectDock()
        self.disconnect_map_tool(restore_previous=True)
        self.cleanup_canvas_items(destroy=True)
        self.cleanup_plot_widget()
        self.remove_dock()
        self.remove_actions()
        self.remove_toolbar()

    # --------------------------------------------------------------------------

    def run(self):
        """Run method that loads and starts the plugin"""
        """execute when the plugin button get hit"""

        if self.pluginIsActive:
            self.line_profile_action.setChecked(True)
            return

        self.pluginIsActive = True

        if getattr(self, "dock", None) is None:
            # Create the dockwidget (after translation) and keep reference
            self.dock = DockWidget(self.iface.mainWindow(), self.iface, self.model)
            self.dock.showDockWidget()
            self.dockOpened = True
            self.dock.setEnabled(True)
            self.dock.closingPlugin.connect(self.onClosePlugin)

            # Create plot area and add to the widget
            self.plotTool.addPlotWidget(self.dock.myFrame)
            self.init_profile_line()

            # Create UI-Action connections
            self.connectDock()

        # self.refreshProfileLines()
        self.init_map_tool()
        self.profileLineTool.show_profile_line()
        if self.dock.ChkBox_Tracer.isChecked():
            self.profileLineTool.init_tracking_marker()

    def refreshProfileLines(self):
        self.profileLineTool.show_profile_line()

    def init_map_tool(self):
        self.prev_tool = self.canvas.mapTool()
        self.line_profile_action.setChecked(True)

        self.dock.setEnabled(True)

        # set canvas maptool to profileline tool
        self.canvas.setMapTool(self.profileLineTool)

        # create connection between changing maptool event and actoin (mapToolChanged)
        self.canvas.mapToolSet.connect(self.mapToolChanged)

    def mapToolChanged(self, current_maptool, old_maptool):
        # changed to LineProfileTool
        old_maptool
        if re.search(r"LineProfileTool", str(current_maptool)):
            if getattr(self, "dock", None) is not None:
                self.dock.setEnabled(True)
            return

        # changed to other tools
        try:
            self.disconnect_map_tool(restore_previous=False)
            self.cleanup_canvas_items(destroy=False)
            self.line_profile_action.setChecked(False)
            if getattr(self, "dock", None) is not None:
                self.dock.setEnabled(False)
            self.pluginIsActive = False
        except (RuntimeError, TypeError, AttributeError) as error:
            self.log_message("Map tool cleanup failed: {}".format(error))

    def connectTools(self):
        self.profileLineTool.proflineterminated.connect(self.handle_terminate_profile_line)
        self.profileLineTool.doubleClicked.connect(self.resetPlot)

    def disconnectTools(self):
        try:
            self.profileLineTool.proflineterminated.disconnect(self.handle_terminate_profile_line)
        except (RuntimeError, TypeError):
            pass
        try:
            self.profileLineTool.doubleClicked.disconnect(self.resetPlot)
        except (RuntimeError, TypeError):
            pass

    def myConnect(self, changed_item=None):
        if (
            changed_item is not None
            and hasattr(changed_item, "column")
            and changed_item.column() == self.model.getColumnIndex("config")
            and self.refresh_cached_processed_profiles()
        ):
            self.update_area_sampling_list()
            self.refresh_peak_data_sources()
            return
        self.updatePlot()
        self.update_area_sampling_list()
        self.refresh_peak_data_sources()

    def connectDock(self):
        self.disconnectTools()
        self.connectTools()

        self.disconnectDock()
        self.setup_points_menu()

        # self.dock.closed.connect(self.closePlugin)
        self.dock.showConfig.connect(self.showConfigDialog)
        # self.dock.resized.connect(self.updatePlot)
        self.dock.resized.connect(self.windowResizeEvent)

        self.dock.myExportProfileLineBtn.clicked.connect(self.openExportProfileLineDialog)
        self.dock.Btn_ImportProfileLine.clicked.connect(self.openImportProfileLineDialog)
        self.dock.Btn_ExportPlot.clicked.connect(self.exportPlot)
        self.dock.ChkBox_TieLine.stateChanged.connect(self.updatePlot)
        self.dock.ChkBox_Tracer.stateChanged.connect(self.handle_toggle_tracking_marker)
        self.dock.Chk_SyncMapExtent.stateChanged.connect(self.handle_map_extent_sync_changed)
        self.dock.ChkBox_ShowSamplingPoints.stateChanged.connect(self.handle_sampling_point_display)
        self.dock.ChkBox_ShowSamplingAreas.stateChanged.connect(self.handle_sampling_area_display)
        self.dock.Btn_ExportProfileData.clicked.connect(self.exportProfileData)
        self.dock.CmbBox_ProfileLine.currentIndexChanged.connect(self.changeCurrentProfileLine)

        self.dock.Btn_ResetProfileLine.clicked.connect(self.clear_profile_line)

        self.dock.Spn_PixelSize.valueChanged.connect(self.update_pixel_size)

        self.dock.Grp_Normalized.clicked.connect(self.updatePlot)
        self.dock.Rdo_By_Total_Length.clicked.connect(self.updatePlot)
        self.dock.Rdo_By_Segment.clicked.connect(self.updatePlot)

        self.dock.Btn_OpenAlignmentFile.clicked.connect(self.import_alignment_file)

        self.dock.Cmb_PeakDataSource.currentIndexChanged.connect(self.handle_peak_context_changed)
        self.dock.Cmb_ProminenceMode.currentIndexChanged.connect(self.handle_prominence_mode_changed)
        self.dock.Cmb_DetectionScope.currentIndexChanged.connect(self.handle_detection_scope_changed)
        self.dock.Txt_DetectionRanges.editingFinished.connect(self.handle_detection_ranges_edited)
        self.dock.Btn_PickDetectionRange.toggled.connect(self.handle_detection_range_pick_toggled)
        self.dock.Btn_AutoDetect.clicked.connect(self.handle_auto_detect)
        self.dock.Btn_ClearAuto.clicked.connect(self.clear_auto_features)
        self.dock.Btn_ClearInScope.clicked.connect(self.clear_features_in_scope)
        self.dock.Chk_ShowFeaturePoints.stateChanged.connect(self.refresh_feature_map_markers)
        self.dock.Btn_ClearAllFeatures.clicked.connect(self.clear_all_features)
        QgsProject.instance().layersRemoved.connect(self.handle_project_layers_removed)

        # model
        self.model.itemChanged.connect(self.myConnect)
        self.model.rowsInserted.connect(self.myConnect)
        self.model.rowsRemoved.connect(self.myConnect)

        # timers
        self.timer_pixel_size_spin_box.timeout.connect(self.updatePlot)
        self.timer_resize_widget.timeout.connect(self.updatePlot)
        self.timer_map_extent.timeout.connect(self.redraw_plot_for_map_extent)
        self.canvas.extentsChanged.connect(self.handle_map_extent_changed)
        self.refresh_peak_data_sources()
        self.handle_prominence_mode_changed()
        self.handle_detection_scope_changed()
        self.update_feature_count()

    def disconnectDock(self):
        if getattr(self, "dock", None) is None:
            self.stop_plugin_timers()
            return
        connections = (
            (self.dock.showConfig, self.showConfigDialog),
            (self.dock.resized, self.windowResizeEvent),
            (self.dock.myExportProfileLineBtn.clicked, self.openExportProfileLineDialog),
            (self.dock.Btn_ImportProfileLine.clicked, self.openImportProfileLineDialog),
            (self.dock.Btn_ExportPlot.clicked, self.exportPlot),
            (self.dock.ChkBox_TieLine.stateChanged, self.updatePlot),
            (self.dock.ChkBox_Tracer.stateChanged, self.handle_toggle_tracking_marker),
            (self.dock.Chk_SyncMapExtent.stateChanged, self.handle_map_extent_sync_changed),
            (self.dock.ChkBox_ShowSamplingPoints.stateChanged, self.handle_sampling_point_display),
            (self.dock.ChkBox_ShowSamplingAreas.stateChanged, self.handle_sampling_area_display),
            (self.dock.Btn_ExportProfileData.clicked, self.exportProfileData),
            (self.dock.CmbBox_ProfileLine.currentIndexChanged, self.changeCurrentProfileLine),
            (self.dock.Btn_ResetProfileLine.clicked, self.clear_profile_line),
            (self.dock.Spn_PixelSize.valueChanged, self.update_pixel_size),
            (self.dock.Grp_Normalized.clicked, self.updatePlot),
            (self.dock.Rdo_By_Total_Length.clicked, self.updatePlot),
            (self.dock.Rdo_By_Segment.clicked, self.updatePlot),
            (self.dock.Btn_OpenAlignmentFile.clicked, self.import_alignment_file),
            (self.dock.Cmb_PeakDataSource.currentIndexChanged, self.handle_peak_context_changed),
            (self.dock.Cmb_ProminenceMode.currentIndexChanged, self.handle_prominence_mode_changed),
            (self.dock.Cmb_DetectionScope.currentIndexChanged, self.handle_detection_scope_changed),
            (self.dock.Txt_DetectionRanges.editingFinished, self.handle_detection_ranges_edited),
            (self.dock.Btn_PickDetectionRange.toggled, self.handle_detection_range_pick_toggled),
            (self.dock.Btn_AutoDetect.clicked, self.handle_auto_detect),
            (self.dock.Btn_ClearAuto.clicked, self.clear_auto_features),
            (self.dock.Btn_ClearInScope.clicked, self.clear_features_in_scope),
            (self.dock.Chk_ShowFeaturePoints.stateChanged, self.refresh_feature_map_markers),
            (self.dock.Btn_ClearAllFeatures.clicked, self.clear_all_features),
            (QgsProject.instance().layersRemoved, self.handle_project_layers_removed),
            (self.model.itemChanged, self.myConnect),
            (self.model.rowsInserted, self.myConnect),
            (self.model.rowsRemoved, self.myConnect),
            (self.timer_pixel_size_spin_box.timeout, self.updatePlot),
            (self.timer_resize_widget.timeout, self.updatePlot),
            (self.timer_map_extent.timeout, self.redraw_plot_for_map_extent),
            (self.canvas.extentsChanged, self.handle_map_extent_changed),
        )
        self.stop_plugin_timers()
        for signal, callback in connections:
            try:
                signal.disconnect(callback)
            except (RuntimeError, TypeError):
                continue
        for action, callback in self.point_menu_actions:
            try:
                action.triggered.disconnect(callback)
            except (RuntimeError, TypeError):
                continue
        self.point_menu_actions = []

    def setup_points_menu(self):
        """Attach a compact, per-dock Points menu without retaining old signals."""
        menu = QMenu(self.dock)
        for label, callback in (
            ("Import Points...", self.import_feature_points),
            ("Export Current Points...", self.export_current_feature_points),
            ("Export All Points...", self.export_all_feature_points),
            ("Create Point Layer", self.create_feature_point_layer),
        ):
            action = QAction(label, menu)
            action.triggered.connect(callback)
            menu.addAction(action)
            self.point_menu_actions.append((action, callback))
        self.dock.Btn_PointsMenu.setMenu(menu)

    def switch_plot_logo(self, show_plot):
        if show_plot:
            self.dock.myFrame_2.show()
            self.dock.widget_3.show()
            self.dock.label_2.hide()
        else:
            self.dock.myFrame_2.hide()
            self.dock.widget_3.show()
            self.dock.label_2.show()

    def showConfigDialog(self, index):
        self.configPlotDialog = LPConfigPlotDialog(self.iface, self.model, index)
        self.configPlotDialog.show()

    def refreshModel(self):
        tree_root = QgsProject.instance().layerTreeRoot()
        # layers = legend.layers()
        layers = [layer for layer in QgsProject.instance().mapLayers().values()]
        layerIds = [layer.id() for layer in layers]
        removeRows = []
        visRows = {}
        for r in range(self.model.rowCount()):
            lid = self.model.getLayerId(r)
            # exist vs. not exist
            if lid not in layerIds:
                removeRows.append(r)
            else:
                # visible vs. not visible
                state = tree_root.findLayer(lid).isVisible()
                # state = legend.isLayerVisible(layers[layerIds.index(lid)])
                mState = self.model.getCheckState(r)

                if state is False and mState == 2:
                    visRows[r] = 0
                    self.model.setCheckState(r, 0)

        removeRows.reverse()
        self.model.updateFlag = False
        [self.model.removeRows(r, 1) for r in removeRows]
        [self.model.setCheckState(r, s) for r, s in iter(visRows.items())]
        self.model.updateFlag = True
        if removeRows or visRows:
            self.updatePlot()

    def handle_project_layers_removed(self, *args):
        self.refreshModel()
        self.refresh_peak_data_sources()
        self.clear_removed_feature_sources()
        self.refresh_feature_map_markers()
        self.update_feature_count()

    def save_plot(self):
        self.exportPlot()

    def exportPlot(self):
        default_file_name = "line_profile_image"
        project_path = QgsProject.instance().readPath("./")
        fileName, _ = QFileDialog.getSaveFileName(
            self.iface.mainWindow(),
            "Save As",
            os.path.join(project_path, default_file_name),
            "Portable Document Format (*.pdf);;\
                                               Image - PNG file (*.png);;\
                                               Image - JPEG file (*.jpg);;\
                                               Scalable Vector Graphics (*.svg)",
        )
        if fileName:
            self.draw_current_plot()
            self.plotTool.savePlot(fileName)

    def windowResizeEvent(self):
        self.timer_resize_widget.start(500)

    def windowResizeEventTimeOut(self):
        if self.windowResizeState:
            pass

    def is_profileline_available(self, profile_line_points):
        n_points = 0
        for p in profile_line_points:
            n_points += len(p)
        return n_points != 0

    def show_alert_non_0_for_pixel_size(self):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)

        msg.setText("Pixel size must be greater than 0")
        msg.setInformativeText("This is additional information")
        msg.setWindowTitle("Error: Pixel Size")
        msg.setStandardButtons(QMessageBox.Ok)
        msg.exec_()

    def update_pixel_size(self, pixel_size):
        if pixel_size == 0:
            self.show_alert_non_0_for_pixel_size()
            self.dock.Spn_PixelSize.setValue(self.dpTool.pixel_size)
            return

        self.dpTool.pixel_size = pixel_size
        self.timer_pixel_size_spin_box.start(1000)

        # print('pixel size: ', self.dpTool.pixel_size)

    def get_raster_layer_id(self, row, layer_id, element_name):
        return "{}_{}_{}".format(row, layer_id[-8:], element_name)

    @staticmethod
    def sampling_signature(config):
        """Return settings that require sampled raw data to be regenerated."""
        return (
            bool(config["fullRes"]),
            bool(config["areaSampling"]),
            config["areaSamplingWidth"],
            config["maxDistance"],
        )

    @staticmethod
    def descriptor_config(config):
        """Keep cached descriptors independent from subsequently edited configs."""
        copied = dict(config)
        copied["plotOptions"] = dict(config["plotOptions"])
        return copied

    def requires_scipy_smoothing(self):
        """Whether an enabled raster series needs SciPy to be rendered."""
        for row in range(self.model.rowCount()):
            if not self.model.getCheckState(row) or not self.model.getLayerType(row):
                continue
            config = self.model.getConfigs(row)
            mode = smoothing_mode(config)
            requires_gaussian = (
                mode == SMOOTHING_GAUSSIAN
                and float(config.get("gaussianSigmaUm", 0.0)) > 0
            )
            requires_savgol = (
                mode == SMOOTHING_SAVGOL
                and float(config.get("savgolWindowUm", 0.0)) > 0
            )
            if requires_gaussian or requires_savgol:
                return True
        return False

    @staticmethod
    def processed_profile_data(data, config):
        """Make one shared processed copy while preserving sampled raw data."""
        return process_profile(data, config)

    def refresh_cached_processed_profiles(self):
        """Reprocess cached raw profiles when only display processing changed."""
        if not self.plotData or not self.pLines:
            return False
        descriptors = [
            descriptor
            for profile_data in self.plotData
            for descriptor in profile_data
        ]
        if not descriptors:
            return False
        for descriptor in descriptors:
            config = self.model.getConfigs(descriptor["row"])
            if descriptor.get("sampling_signature") != self.sampling_signature(config):
                return False
        if self.requires_scipy_smoothing() and not self.scipyDependencyManager.has_scipy():
            self.scipyDependencyManager.ensure_scipy(
                self.iface.mainWindow(), self.refresh_cached_processed_profiles
            )
            return True
        for profile_index, profile_data in enumerate(self.plotData):
            for descriptor in profile_data:
                config = self.model.getConfigs(descriptor["row"])
                descriptor["configs"] = self.descriptor_config(config)
                descriptor["processed_data"] = self.processed_profile_data(
                    descriptor["data"], config
                )
                if descriptor.get("raster_layer_id") is not None:
                    signature = self.make_feature_data_signature(
                        profile_index,
                        self.pLines[profile_index],
                        descriptor["layer"],
                        descriptor["label"],
                        config,
                    )
                    self.register_feature_data_signature(
                        profile_index, descriptor["raster_layer_id"], signature
                    )
        self.draw_current_plot()
        self.refresh_feature_map_markers()
        self.update_feature_count()
        return True

    def updatePlot(self):
        """sampling/correct data from raster and vector layers along with profile line,
        then create/update plot
        """
        if not self.model.updateFlag:
            self.pLines = []
            self.switch_plot_logo(False)
            return

        if self.canvas.layerCount() == 0 or self.model.rowCount() == 0:
            self.pLines = []
            self.profileLineTool.reset_all_profile()
            self.featurePointStore.clear_all()
            self.feature_data_signatures.clear()
            # self.profileLineTool.resetProfileLine()
            self.plotTool.resetPlot(1)
            self.switch_plot_logo(False)
            self.refresh_peak_data_sources()
            self.update_feature_count()
            return

        if self.requires_scipy_smoothing() and not self.scipyDependencyManager.has_scipy():
            self.scipyDependencyManager.ensure_scipy(
                self.iface.mainWindow(), self.updatePlot
            )
            return

        self.pLines = []

        profPoints = self.profileLineTool.get_all_profile_points()
        for profile_index, points in enumerate(profPoints):
            if len(points) < 2:
                self.featurePointStore.clear_profile(profile_index)
                self.dpTool.clear_profile_sample_centers(profile_index)
                for key in [key for key in self.feature_data_signatures if key[0] == profile_index]:
                    self.feature_data_signatures.pop(key, None)

        # self.pLines = []
        if not self.is_profileline_available(profPoints):
            # reset plot
            self.plotTool.resetPlot(clearAll=True)
            self.switch_plot_logo(False)
            self.refresh_feature_map_markers()
            self.update_feature_count()
            return

        for pIndex in range(len(profPoints)):
            pp = profPoints[pIndex]
            self.updateProfileLineData(pIndex, pp)
            self.pLines.append(self.dpTool.getProfileLines(pp))

        if reduce(lambda x, y: x + len(y), self.pLines, 0) == 0:
            self.switch_plot_logo(False)
            self.refresh_feature_map_markers()
            self.update_feature_count()
            return False

        self.switch_plot_logo(True)

        # initialize tie lines
        self.dpTool.initTieLines()
        [self.profileLineTool.reset_tielines(pIndex) for pIndex in range(self.n_profile_lines)]

        # reset sampling ranges
        # self.profileLineTool.resetSamplingRange()

        # initialize sampling points on raster layer for debugging
        self.dpTool.initSamplingPoints()
        self.dpTool.initSamplingArea()

        self.plotData = []
        # distLimit = self.dock.SpnBox_DistanceLimit.value()
        for pIndex in range(len(self.pLines)):
            pp = self.pLines[pIndex]
            if not len(pp):
                self.plotData.append([])
                continue
            data = []
            for r in range(self.model.rowCount()):
                layer = self.getLayerById(self.model.getLayerId(r))
                if not layer or not self.model.getCheckState(r):
                    continue

                field = self.model.getDataName(r)
                config = self.model.getConfigs(r)
                label = self.model.getDataName(r)
                color_org = self.model.getColorName(r)
                layer_type = layer.type()

                myData = []
                raster_layer_id = None
                if layer_type == layer.VectorLayer:
                    """Vector Layer"""
                    myData = self.dpTool.getVectorProfile(pp, layer, field, config["maxDistance"], None, pIndex)

                elif layer_type == layer.RasterLayer:
                    """Raster Layer"""
                    equi_width = int(config["areaSampling"]) * config["areaSamplingWidth"]
                    raster_layer_id = self.get_raster_layer_id(r, layer.id(), label)
                    myData = self.dpTool.getRasterProfile(
                        pp, layer, field, config["fullRes"], raster_layer_id, equi_width, pIndex
                    )
                    # draw raster sampling area and pionts

                data.append(
                    {
                        "data": myData,
                        "processed_data": self.processed_profile_data(myData, config),
                        "label": label,
                        "configs": self.descriptor_config(config),
                        "layer": layer,
                        "layer_type": layer_type,
                        "color_org": color_org,
                        "row": r,
                        "raster_layer_id": raster_layer_id,
                        "sampling_signature": self.sampling_signature(config),
                    }
                )
                if raster_layer_id is not None:
                    signature = self.make_feature_data_signature(
                        pIndex, pp, layer, field, config
                    )
                    self.register_feature_data_signature(
                        pIndex, raster_layer_id, signature
                    )
            # self.handle_raster_sampling_details(pIndex, config, color_org)
            self.plotData.append(data)

        self.refresh_peak_data_sources()
        self.clear_removed_feature_sources()

        # draw tie lines
        if self.dock.ChkBox_TieLine.isChecked():
            self.profileLineTool.draw_tieline(self.dpTool.getTieLines())

        # draw sampling points and areas
        self.handle_sampling_point_display()
        self.handle_sampling_area_display()
        # draw sampling points on raster layer for debugging
        # if self.debugFlag is True:
        #     for pt in self.dpTool.getSamplingPoints():
        #         self.profileLineTool.addVertex5(pt)

        # self.profileLineTool.updateProfileLine()

        self.draw_current_plot()
        self.refresh_feature_map_markers()
        self.update_feature_count()

    def draw_current_plot(self):
        """Render the currently cached profile geometry and sampled data."""
        if not getattr(self, "dock", None) or not self.pLines or not self.plotData:
            return

        normalized = self.dock.Grp_Normalized.isChecked()
        normalized_by_segment = self.dock.Rdo_By_Segment.isChecked()
        if not self.handle_normalization(normalized, normalized_by_segment):
            return

        visible_ranges = None
        if self.dock.Chk_SyncMapExtent.isChecked():
            visible_ranges = self.get_visible_profile_ranges()
        self.current_visible_profile_ranges = visible_ranges

        self.plotTool.drawPlot3(
            self.pLines,
            self.plotData,
            pLineNormalized=normalized,
            pLineNormalizedBySegment=normalized_by_segment,
            profilePlotConverter=self.ppc,
            featureRecords=self.current_feature_records(),
            featureProfileIndex=self.getProfileIndex(),
            featureRasterLayerId=self.current_peak_raster_layer_id(),
            visibleProfileRanges=visible_ranges,
            detectionScopeRanges=self.current_detection_ranges(),
            detectionScopeProfileIndex=self.getProfileIndex(),
        )

    def get_visible_profile_ranges(self):
        return visible_profile_ranges(self.pLines, self.canvas.extent())

    def handle_map_extent_changed(self):
        if (
            not self.pluginIsActive
            or not getattr(self, "dock", None)
            or not (
                self.dock.Chk_SyncMapExtent.isChecked()
                or self.current_detection_scope() == SCOPE_CURRENT_MAP_EXTENT
            )
            or not self.pLines
            or not self.plotData
        ):
            return
        self.timer_map_extent.start()

    def handle_map_extent_sync_changed(self, *args):
        self.timer_map_extent.stop()
        if self.pLines and self.plotData:
            self.draw_current_plot()

    def redraw_plot_for_map_extent(self):
        if (
            self.pluginIsActive
            and getattr(self, "dock", None)
            and (
                self.dock.Chk_SyncMapExtent.isChecked()
                or self.current_detection_scope() == SCOPE_CURRENT_MAP_EXTENT
            )
            and self.pLines
            and self.plotData
        ):
            self.draw_current_plot()

    def show_error_message_on_normaliziation(self, text):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Warning)
        msg.setText(text)
        msg.setWindowTitle("Error: Normalization")
        msg.exec_()
        pass

    def handle_sampling_point_display(self):
        """handle show/hide sampling points"""

        self.hide_all_sampling_points()
        if self.dock.ChkBox_ShowSamplingPoints.isChecked():
            [
                self.show_sampling_points(profile_index)
                for profile_index in range(self.n_profile_lines)
                if len(self.profileLineTool.profile[profile_index]["point"])
            ]

    def show_sampling_points(self, profile_index):
        """draw sampling points"""
        current_id = self.dock.ChkBox_Area_Sampling_Element.currentIndex()
        layer_id = self.dock.ChkBox_Area_Sampling_Element.itemData(current_id)
        ks = self.dpTool.sampling_points[profile_index].keys()

        if layer_id in ks:
            sampling_pts = self.dpTool.sampling_points[profile_index][layer_id]
            self.profileLineTool.add_sampling_points(profile_index, sampling_pts)

    def hide_all_sampling_points(self):
        [self.hide_sampling_points(profile_index) for profile_index in range(self.n_profile_lines)]

    def hide_sampling_points(self, profile_index):
        self.profileLineTool.reset_sampling_points(profile_index)

    def handle_sampling_area_display(self):
        """handle show/hide sampling areas"""
        self.hide_all_sampling_areas()
        if self.dock.ChkBox_ShowSamplingAreas.isChecked():
            [
                self.show_sampling_areas(profile_index)
                for profile_index in range(self.n_profile_lines)
                if len(self.profileLineTool.profile[profile_index]["point"])
            ]

    def show_sampling_areas(self, profile_index):
        """draw sampling areas belong to specified profile line"""
        current_id = self.dock.ChkBox_Area_Sampling_Element.currentIndex()
        layer_id = self.dock.ChkBox_Area_Sampling_Element.itemData(current_id)
        ks = self.dpTool.sampling_points[profile_index].keys()

        if layer_id in ks:
            sampling_areas = self.dpTool.sampling_areas[profile_index][layer_id]
            self.profileLineTool.add_sampling_areas(profile_index, sampling_areas)

    def hide_all_sampling_areas(self):
        """remove all sampling areas for all profile lines"""
        [self.hide_sampling_areas(profile_index) for profile_index in range(self.n_profile_lines)]

    def hide_sampling_areas(self, profile_index):
        """remove sampling area belong to specified profile line"""
        self.profileLineTool.reset_sampling_areas(profile_index)

    def handle_raster_sampling_details(self, p_index, config, color_org):
        """draw raster sampling area and points"""

        self.profileLineTool.reset_sampling_areas(p_index)
        self.profileLineTool.reset_raster_sampling_points(p_index)

        if config["areaSampling"]:
            # add sampling area
            if self.dock.ChkBox_ShowSamplingAreas.isChecked():
                self.profileLineTool.add_sampling_areas(self.dpTool.getSamplingArea(), color_org)

            # add sampling points
            if self.dock.ChkBox_ShowSamplingPoints.isChecked():
                for pt in self.dpTool.getSamplingRange():
                    self.profileLineTool.add_sampling_points(pt, color_org)

    def resetPlot(self):
        resetAllFlag = False
        if reduce(lambda x, y: x + len(y), self.profileLineTool.getAllProfPoints(), 0) == 0:
            resetAllFlag = True
        self.plotTool.resetPlot(resetAllFlag)
        self.updatePlot()

    def handle_normalization(self, normalized, normalized_by_segment):
        """check profile lines whether normalizable or not"""
        if normalized and normalized_by_segment:
            n_seg = len(self.pLines[0])
            for i in range(1, len(self.pLines)):
                if n_seg != len(self.pLines[i]):
                    # Show message (need to have same number of segment)
                    self.show_error_message_on_normaliziation("Need same number of segments.")
                    return False
            try:
                self.ppc.set_pLines(self.pLines, 0)
            except ValueError as error:
                self.show_error_message_on_normaliziation(str(error))
                return False

        if normalized:
            for i in range(self.n_profile_lines):
                if len(self.pLines[i]) == 0:
                    # Show message (need to have same number of segment)
                    self.show_error_message_on_normaliziation("At least two profile line needed.")
                    return False
        return True

    def openExportProfileLineDialog(self):
        self.expPLDialog = LPExportDialog()
        self.expPLDialog.show()
        res = self.expPLDialog.exec_()
        if not res:
            return

        if self.expPLDialog.Grp_SaveShapeFileAs.isChecked():
            shapeFilePath = self.sanitizePath(self.expPLDialog.shapeFileName)
            self.exportProfileLineAsShapeFile(shapeFilePath)
        if self.expPLDialog.Grp_AddField.isChecked():
            self.addDistanceToAttribute()

    def exportProfileLineAsShapeFile(self, shapeFilePath):
        fields = []
        polyline = []
        attr = []
        fileName = os.path.splitext(os.path.basename(shapeFilePath))[0]
        profileLineLayer = QgsVectorLayer("LineString", fileName, "memory")

        profileLineLayer.startEditing()
        dataProvider = profileLineLayer.dataProvider()

        # get point of current profile line
        points = self.profileLineTool.get_profile_points()

        # add fields
        for i in range(len(points)):
            fields.append(QgsField("Point-{0}".format(i + 1), QVariant.String))
        fields.append(QgsField("Max Dist.", QVariant.Double))
        dataProvider.addAttributes(fields)

        # get rofile line features
        for pt in points:
            polyline.append(QgsPoint(*pt))
            attr.append("{0}, {1}".format(*pt))

        # add a feature
        feture = QgsFeature()
        feture.setGeometry(QgsGeometry.fromPolyline(polyline))
        feture.setAttributes(attr)
        dataProvider.addFeatures([feture])

        # update layer's extent when new features have been added
        # because change of extent in provider is not propagated to the layer
        profileLineLayer.commitChanges()
        profileLineLayer.updateExtents()

        # save shape file
        error, _ = QgsVectorFileWriter.writeAsVectorFormat(
            profileLineLayer, shapeFilePath, "UTF-8", driverName="ESRI Shapefile"
        )
        if error == QgsVectorFileWriter.NoError:
            if self.expPLDialog.ChkBox_AddSavedFileToMap.isChecked():
                # add shape file to map
                self.iface.addVectorLayer(shapeFilePath, fileName, "ogr")
        else:
            self.log_message("Profile line export failed with error code {}".format(error), Qgis.Critical)
            QMessageBox.warning(self.iface.mainWindow(), "Line Profile", "Could not export the profile line.")

    def is_vector_layer_available(self, layer, model, r):
        if not layer:
            return False
        if layer.type() != layer.VectorLayer:
            return False
        if not model.getCheckState(r):
            return False
        return True

    def addDistanceToAttribute(self):
        newFieldName = self.expPLDialog.TBox_FieldName.text()

        for r in range(self.model.rowCount()):
            layer = self.getLayerById(self.model.getLayerId(r))

            if not self.is_vector_layer_available(layer, self.model, r):
                continue

            field = self.model.getDataName(r)
            config = self.model.getConfigs(r)
            pIndex = self.getProfileIndex()
            dataProvider = layer.dataProvider()
            dataProvider.addAttributes([QgsField(newFieldName, QVariant.Double)])
            layer.updateFields()
            self.dpTool.getVectorProfile(self.pLines[pIndex], layer, field, config["maxDistance"], newFieldName, pIndex)

    def openImportProfileLineDialog(self):
        self.impPLDialog = LPImportDialog(self.iface)
        self.impPLDialog.show()

        if not self.impPLDialog.exec_():
            return

        if self.impPLDialog.RadBtn_FileSelect.isChecked():
            shapeFilePath = self.sanitizePath(self.impPLDialog.TBox_ShapeFilePath.text())
            shapeFileName = os.path.splitext(os.path.basename(shapeFilePath))[0]
            layer = self.iface.addVectorLayer(shapeFilePath, shapeFileName, "ogr")
        else:
            layerId = self.impPLDialog.CmbBox_LayerSelect.itemData(self.impPLDialog.CmbBox_LayerSelect.currentIndex())
            layer = self.getLayerById(layerId)
        self.importProfileLine(layer)

    def importProfileLine(self, layer):
        if not layer or not layer.isValid():
            QMessageBox.warning(self.iface.mainWindow(), "Line Profile", "Could not open the profile line layer.")
            return
        dp = layer.dataProvider()
        points = []
        for f in dp.getFeatures():
            geometry = f.geometry()
            if geometry.isMultipart():
                multipart = geometry.asMultiPolyline()
                points = multipart[0] if multipart else []
            else:
                points = geometry.asPolyline()
            break
        if len(points) < 2:
            QMessageBox.warning(self.iface.mainWindow(), "Line Profile", "The selected layer has no usable line geometry.")
            return
        points = [[pt.x(), pt.y()] for pt in points]
        self.profileLineTool.draw_profileLine_from_points(points)
        self.updatePlot()

    def init_profile_line(self):
        self.dock.CmbBox_ProfileLine.clear()
        for i in range(self.n_profile_lines):
            self.dock.CmbBox_ProfileLine.addItem("Profile Line {}".format(i + 1), i)
        self.dock.CmbBox_ProfileLine.setCurrentIndex(0)

        if not self.profileLineTool.profile:
            self.profileLineTool.init_profile(self.n_profile_lines)

    def clear_profile_line(self):
        # self.profileLineTool.resetProfileLine()
        profile_index = self.getProfileIndex()
        self.featurePointStore.clear_profile(profile_index)
        self.dpTool.clear_profile_sample_centers(profile_index)
        self.profileLineTool.reset_feature_points(profile_index)
        self.profileLineTool.reset_profile(profile_index)
        self.updatePlot()

    def removeProfileLine(self):
        """remove second profile line"""
        pass

    def changeCurrentProfileLine(self, pIndex):
        self.profileLineTool.update_current_profile_line(pIndex)
        self.pending_detection_range_start = None
        if getattr(self, "dock", None):
            self.dock.Btn_PickDetectionRange.setText("Pick")
            self.refresh_detection_range_editor()
        if hasattr(self, "plotData"):
            self.updatePlot()

    def getProfileIndex(self):
        return self.dock.CmbBox_ProfileLine.currentIndex()

    def updateProfileLineData(self, pIndex, data):
        self.dock.CmbBox_ProfileLine.setItemData(pIndex, data)
        self.profileLineTool.terminated = True

    def check_tracer_condition(self, event, pIndex, normFactor):
        res = (
            not self.dock.ChkBox_Tracer.isChecked()
            or event.xdata is None
            or event.ydata is None
            or len(self.pLines) < pIndex
            or len(normFactor) <= pIndex
        )
        return res

    def handle_toggle_tracking_marker(self, state):
        if state:
            self.profileLineTool.init_tracking_marker()
        else:
            self.profileLineTool.reset_tracking_marker()

    def is_trace_marker_available(self, event):
        if not self.dock.ChkBox_Tracer.isChecked():
            return False

        if event.xdata is None or event.ydata is None:
            return False

        if len(self.profileLineTool.profile[self.profileLineTool.profile_line_index]["point"]) == 0:
            return False

        return True

    def draw_trace_marker(self, event, normFactor):
        # self.profileLineTool.reset_tracing_marker()
        if not self.is_trace_marker_available(event):
            # hide marker
            self.profileLineTool.hide_tracking_marker()
            return

        p_index = self.profileLineTool.profile_line_index
        # show marker
        self.profileLineTool.show_tracking_marker()

        # move marker to the position

        x = self.plot_x_to_profile_x(event.xdata, p_index, normFactor)

        if self.current_visible_profile_ranges is not None and not distance_in_ranges(
            x, self.current_visible_profile_ranges.get(p_index, [])
        ):
            self.profileLineTool.hide_tracking_marker()
            return

        if x > self.dpTool.sumD(self.pLines[p_index]):
            return
        pt = self.dpTool.getCurrentCoordinates(self.pLines[p_index], x)
        self.profileLineTool.update_tracking_marker(pt)

    def is_normalized_by_segment(self):
        return self.dock.Grp_Normalized.isChecked() and self.dock.Rdo_By_Segment.isChecked()

    def drawTracer(self, event, normFactor):
        self.draw_trace_marker(event, normFactor)
        return
        # self.profileLineTool.resetRasterPoints()
        # self.profileLineTool.reset_tracing_marker()
        # pIndex = self.dock.CmbBox_ProfileLine.currentIndex()
        # if self.check_tracer_condition(event, pIndex, normFactor):
        #     return
        #
        # x = event.xdata / normFactor[pIndex]
        #
        # if self.dpTool.sumD(self.pLines[pIndex]) < x:
        #     return
        #
        # pt = self.dpTool.getCurrentCoordinates(self.pLines[pIndex], x)
        # self.profileLineTool.add_tracing_marker(pt)

    def handle_terminate_profile_line(self):
        # update profile-plot converter
        self.updatePlot()

    def exportProfileData(self):
        fileName, _ = QFileDialog.getSaveFileName(
            self.iface.mainWindow(),
            "Save As",
            os.environ["HOME"],
            "Tab Delimited Text (*.txt);; Comma Separated Values (*.csv)",
        )
        if fileName:
            myD = []
            myL = 0
            out = []
            _, file_format = os.path.splitext(fileName)
            if file_format == ".txt":
                sep = "\t"
            elif file_format == ".csv":
                sep = ","
            else:
                sep = " "
            pIndex = self.getProfileIndex()
            data = self.plotData[pIndex]
            export_data = []

            for d in data:
                current_data = processed_data(d)
                export_data.append((d, current_data))
                curL = len(current_data[0])
                myL = curL if curL >= myL else myL

            for d, current_data in export_data:
                label = d["layer"].name() + "_" + d["label"]
                # transpose data rows and columns
                a = [list(x) for x in zip(*current_data)]
                curL = len(a)
                # padded by '' for shorter data length
                for _ in range(myL - curL):
                    a.append(["", ""])
                a.insert(0, ["distance (micron)", label])
                myD.append(a)

            for r in range(myL + 1):  # plus 1 for label
                l = []
                for c in myD:
                    l += c[r]
                out.append(sep.join(str(ll) for ll in l))

            with open(fileName, "w") as f:
                f.write("\n".join(out))

    def getLayerById(self, lid):
        l = [layer for layer in self.canvas.layers() if lid == layer.id()]
        return l[0] if len(l) == 1 else False

    def update_area_sampling_list(self):
        my_cbx = self.dock.ChkBox_Area_Sampling_Element
        my_cbx.clear()
        for r in range(self.model.rowCount()):
            element_name = self.model.getDataName(r)
            layer_id = self.model.getLayerId(r)
            layer_type = self.model.getLayerTypeName(r)
            if layer_type == "Vector":
                continue
            raster_layer_id = self.get_raster_layer_id(r, layer_id, element_name)
            my_cbx.addItem(element_name, raster_layer_id)

    def refresh_peak_data_sources(self):
        if not getattr(self, "dock", None):
            return
        combo = self.dock.Cmb_PeakDataSource
        selected_id = combo.currentData()
        combo.blockSignals(True)
        combo.clear()
        for row in range(self.model.rowCount()):
            layer = self.getLayerById(self.model.getLayerId(row))
            if (
                not layer
                or layer.type() != layer.RasterLayer
                or not self.model.getCheckState(row)
            ):
                continue
            data_name = self.model.getDataName(row)
            raster_layer_id = self.get_raster_layer_id(row, layer.id(), data_name)
            combo.addItem("{} — {}".format(layer.name(), data_name), raster_layer_id)
        selected_index = combo.findData(selected_id)
        combo.setCurrentIndex(selected_index if selected_index >= 0 else (0 if combo.count() else -1))
        combo.setToolTip(combo.currentText())
        combo.blockSignals(False)
        has_source = combo.currentIndex() >= 0
        self.dock.Btn_AutoDetect.setEnabled(has_source)
        self.dock.Btn_ModeAddPeak.setEnabled(has_source)
        self.dock.Btn_ModeAddValley.setEnabled(has_source)
        self.dock.Btn_ModeDelete.setEnabled(has_source)

    def current_peak_raster_layer_id(self):
        if not getattr(self, "dock", None):
            return None
        return self.dock.Cmb_PeakDataSource.currentData()

    def current_detection_scope(self):
        scopes = (
            SCOPE_FULL_PROFILE,
            SCOPE_SELECTED_RANGES,
            SCOPE_CURRENT_MAP_EXTENT,
        )
        if not getattr(self, "dock", None):
            return SCOPE_FULL_PROFILE
        index = self.dock.Cmb_DetectionScope.currentIndex()
        return scopes[index] if 0 <= index < len(scopes) else SCOPE_FULL_PROFILE

    def current_prominence_mode(self):
        modes = (
            PROMINENCE_ABSOLUTE,
            PROMINENCE_LOCAL_RANGE,
            PROMINENCE_LOCAL_SD,
            PROMINENCE_LOCAL_MAD,
        )
        if not getattr(self, "dock", None):
            return PROMINENCE_ABSOLUTE
        index = self.dock.Cmb_ProminenceMode.currentIndex()
        return modes[index] if 0 <= index < len(modes) else PROMINENCE_ABSOLUTE

    def handle_prominence_mode_changed(self, *args):
        if not getattr(self, "dock", None):
            return
        mode = self.current_prominence_mode()
        self.dock.updateConditionalControls()
        labels = {
            PROMINENCE_ABSOLUTE: "Minimum",
            PROMINENCE_LOCAL_RANGE: "Range %",
            PROMINENCE_LOCAL_SD: "SD multiplier",
            PROMINENCE_LOCAL_MAD: "MAD multiplier",
        }
        tooltips = {
            PROMINENCE_ABSOLUTE: "Minimum absolute prominence in intensity units; 0 means unconstrained",
            PROMINENCE_LOCAL_RANGE: "Threshold = local (max - min) × percentage / 100; 0 means unconstrained",
            PROMINENCE_LOCAL_SD: "Threshold = multiplier × local standard deviation; 0 means unconstrained",
            PROMINENCE_LOCAL_MAD: "Threshold = multiplier × 1.4826 × local median absolute deviation; 0 means unconstrained",
        }
        self.dock.Lbl_Prominence.setText(labels[mode])
        self.dock.Spn_Prominence.setToolTip(tooltips[mode])
        self.dock.Spn_Prominence.setSuffix(" %" if mode == PROMINENCE_LOCAL_RANGE else "")

    def current_detection_ranges(self, context=None):
        """Return the active scope as raw physical profile-distance ranges."""
        scope = self.current_detection_scope()
        if scope == SCOPE_FULL_PROFILE:
            return None
        profile_index = self.getProfileIndex()
        if scope == SCOPE_SELECTED_RANGES:
            return list(self.detection_ranges.get(profile_index, []))
        if not self.pLines or profile_index < 0 or profile_index >= len(self.pLines):
            return []
        return self.get_visible_profile_ranges().get(profile_index, [])

    def full_detection_ranges(self, context):
        return full_profile_ranges(context["x"])

    def refresh_detection_range_editor(self):
        if not getattr(self, "dock", None):
            return
        ranges = self.detection_ranges.get(self.getProfileIndex(), [])
        self.dock.Txt_DetectionRanges.blockSignals(True)
        self.dock.Txt_DetectionRanges.setText(format_ranges(ranges))
        self.dock.Txt_DetectionRanges.blockSignals(False)

    def handle_detection_scope_changed(self, *args):
        if not getattr(self, "dock", None):
            return
        selected = self.current_detection_scope() == SCOPE_SELECTED_RANGES
        self.pending_detection_range_start = None
        self.dock.updateConditionalControls()
        if not selected:
            self.dock.Btn_PickDetectionRange.setChecked(False)
        self.dock.Btn_PickDetectionRange.setText("Pick")
        self.refresh_detection_range_editor()
        if self.pLines and self.plotData:
            self.draw_current_plot()

    def handle_detection_ranges_edited(self):
        try:
            ranges = parse_ranges(self.dock.Txt_DetectionRanges.text())
        except ValueError as error:
            QMessageBox.warning(
                self.iface.mainWindow(), "Detection Scope", str(error)
            )
            self.refresh_detection_range_editor()
            return
        self.detection_ranges[self.getProfileIndex()] = ranges
        self.pending_detection_range_start = None
        self.dock.Btn_PickDetectionRange.setText("Pick")
        if self.pLines and self.plotData:
            self.draw_current_plot()

    def handle_detection_range_pick_toggled(self, checked):
        self.pending_detection_range_start = None
        self.dock.Btn_PickDetectionRange.setText("Pick" if not checked else "Pick start")

    def handle_detection_range_plot_click(self, raw_distance):
        if self.pending_detection_range_start is None:
            self.pending_detection_range_start = raw_distance
            self.dock.Btn_PickDetectionRange.setText("Pick end")
            return
        profile_index = self.getProfileIndex()
        ranges = self.detection_ranges.get(profile_index, [])
        ranges.append((self.pending_detection_range_start, raw_distance))
        self.detection_ranges[profile_index] = merge_ranges(ranges)
        self.pending_detection_range_start = None
        self.dock.Btn_PickDetectionRange.setText("Pick start")
        self.refresh_detection_range_editor()
        self.draw_current_plot()

    def current_peak_context(self, show_message=False):
        profile_index = self.getProfileIndex()
        raster_layer_id = self.current_peak_raster_layer_id()
        if raster_layer_id is None or not hasattr(self, "plotData"):
            if show_message:
                QMessageBox.information(self.iface.mainWindow(), "Peak / Valley Detection", "Select a raster data series first.")
            return None
        if profile_index < 0 or profile_index >= len(self.plotData):
            return None
        for descriptor in self.plotData[profile_index]:
            if descriptor.get("raster_layer_id") != raster_layer_id:
                continue
            x_values, y_values = processed_data(descriptor)
            centers = self.dpTool.get_profile_sample_centers(profile_index, raster_layer_id)
            if not x_values or len(x_values) != len(y_values) or len(x_values) != len(centers):
                if show_message:
                    QMessageBox.warning(
                        self.iface.mainWindow(),
                        "Peak / Valley Detection",
                        "The selected raster profile has no usable samples or its sample mapping is inconsistent.",
                    )
                return None
            return {
                "profile_index": profile_index,
                "raster_layer_id": raster_layer_id,
                "x": x_values,
                "y": y_values,
                "centers": centers,
                "data_label": "{} — {}".format(descriptor["layer"].name(), descriptor["label"]),
            }
        if show_message:
            QMessageBox.information(self.iface.mainWindow(), "Peak / Valley Detection", "Select a raster data series first.")
        return None

    def make_feature_data_signature(self, profile_index, profile_lines, layer, field, config):
        geometry = tuple(
            (
                tuple(segment["start"]),
                tuple(segment["end"]),
                segment["distance_pixel_sized"],
            )
            for segment in profile_lines
        )
        return (
            profile_index,
            geometry,
            layer.id(),
            field,
            bool(config["fullRes"]),
            bool(config["areaSampling"]),
            config["areaSamplingWidth"],
            self.dpTool.pixel_size,
            smoothing_signature(config),
        )

    def register_feature_data_signature(self, profile_index, raster_layer_id, signature):
        key = (profile_index, raster_layer_id)
        previous = self.feature_data_signatures.get(key)
        if previous is not None and previous != signature:
            self.featurePointStore.clear_key(profile_index, raster_layer_id)
            self.profileLineTool.reset_feature_points(profile_index)
        self.feature_data_signatures[key] = signature

    def clear_removed_feature_sources(self):
        valid_ids = set()
        for row in range(self.model.rowCount()):
            layer = self.getLayerById(self.model.getLayerId(row))
            if not layer or layer.type() != layer.RasterLayer:
                continue
            valid_ids.add(self.get_raster_layer_id(row, layer.id(), self.model.getDataName(row)))
        for profile_index, raster_layer_id in list(self.featurePointStore.keys()):
            if raster_layer_id not in valid_ids:
                self.featurePointStore.clear_key(profile_index, raster_layer_id)
                self.feature_data_signatures.pop((profile_index, raster_layer_id), None)

    def current_feature_records(self):
        raster_layer_id = self.current_peak_raster_layer_id()
        if raster_layer_id is None:
            return []
        return self.featurePointStore.records_for(self.getProfileIndex(), raster_layer_id)

    def update_feature_count(self):
        if getattr(self, "dock", None):
            self.dock.Lbl_FeatureCount.setText("{} points".format(len(self.current_feature_records())))

    def refresh_feature_map_markers(self, *args):
        self.profileLineTool.reset_feature_points()
        if not getattr(self, "dock", None) or not self.dock.Chk_ShowFeaturePoints.isChecked():
            return
        profile_index = self.getProfileIndex()
        records = self.current_feature_records()
        if records and 0 <= profile_index < len(self.profileLineTool.profile):
            self.profileLineTool.draw_feature_points(profile_index, records)

    def handle_peak_context_changed(self, *args):
        if hasattr(self, "plotData"):
            self.updatePlot()
        else:
            self.refresh_feature_map_markers()
            self.update_feature_count()

    def handle_auto_detect(self):
        context = self.current_peak_context(show_message=True)
        if context is None:
            return
        if not self.dock.Chk_DetectPeaks.isChecked() and not self.dock.Chk_DetectValleys.isChecked():
            QMessageBox.information(
                self.iface.mainWindow(),
                "Peak / Valley Detection",
                "Enable Detect Peaks and/or Detect Valleys.",
            )
            return
        scope = self.current_detection_scope()
        ranges = (
            self.full_detection_ranges(context)
            if scope == SCOPE_FULL_PROFILE
            else self.current_detection_ranges(context)
        )
        if not ranges:
            QMessageBox.information(
                self.iface.mainWindow(),
                "Detection Scope",
                "The active detection scope does not contain a profile range.",
            )
            return
        if not self.peakDetectionTool.scipy_available():
            self.scipyDependencyManager.ensure_scipy(self.iface.mainWindow(), self.handle_auto_detect)
            return
        options = {
            "algorithm": self.dock.Cmb_PeakAlgorithm.currentData(),
            **self.dock.cwt_settings,
            "detect_peaks": self.dock.Chk_DetectPeaks.isChecked(),
            "detect_valleys": self.dock.Chk_DetectValleys.isChecked(),
            "prominence": self.dock.Spn_Prominence.value() or None,
            "prominence_mode": self.current_prominence_mode(),
            "prominence_window": self.dock.Spn_AdaptiveWindow.value(),
            "min_distance": self.dock.Spn_MinPeakDistance.value(),
            "min_width": self.dock.Spn_MinPeakWidth.value(),
        }
        try:
            results = (
                self.peakDetectionTool.detect(context["x"], context["y"], **options)
                if scope == SCOPE_FULL_PROFILE
                else detect_in_ranges(
                    self.peakDetectionTool,
                    context["x"],
                    context["y"],
                    ranges,
                    **options
                )
            )
        except (ImportError, ValueError, RuntimeError) as error:
            self.log_message("Peak/Valley detection failed: {}".format(error), Qgis.Critical)
            QMessageBox.warning(self.iface.mainWindow(), "Peak / Valley Detection", str(error))
            return

        records = []
        for kind in ("peak", "valley"):
            for result in results[kind]:
                record = dict(result)
                record.update(
                    {
                        "profile_index": context["profile_index"],
                        "raster_layer_id": context["raster_layer_id"],
                        "point": context["centers"][record["sample_index"]],
                        "data_label": context["data_label"],
                    }
                )
                records.append(record)
        if scope == SCOPE_FULL_PROFILE:
            self.featurePointStore.replace_auto(
                context["profile_index"], context["raster_layer_id"], records
            )
        else:
            self.featurePointStore.replace_auto_in_ranges(
                context["profile_index"], context["raster_layer_id"], records, ranges
            )
        self.updatePlot()

    def clear_auto_features(self):
        raster_layer_id = self.current_peak_raster_layer_id()
        if raster_layer_id is None:
            return
        self.featurePointStore.clear_auto(self.getProfileIndex(), raster_layer_id)
        self.updatePlot()

    def clear_features_in_scope(self):
        context = self.current_peak_context(show_message=True)
        if context is None:
            return
        ranges = (
            self.full_detection_ranges(context)
            if self.current_detection_scope() == SCOPE_FULL_PROFILE
            else self.current_detection_ranges(context)
        )
        if not ranges:
            QMessageBox.information(
                self.iface.mainWindow(),
                "Detection Scope",
                "The active detection scope does not contain a profile range.",
            )
            return
        scoped = self.featurePointStore.records_in_ranges(
            context["profile_index"], context["raster_layer_id"], ranges
        )
        if not scoped:
            return
        curated = [record for record in scoped if record["source"] != "auto"]
        if curated:
            response = QMessageBox.question(
                self.iface.mainWindow(),
                "Peak / Valley Detection",
                "Clear points in the active scope, including {} manual/imported point(s)?".format(
                    len(curated)
                ),
                QMessageBox.Yes | QMessageBox.Cancel,
                QMessageBox.Cancel,
            )
            if response != QMessageBox.Yes:
                return
        self.featurePointStore.clear_in_ranges(
            context["profile_index"],
            context["raster_layer_id"],
            ranges,
            include_curated=True,
        )
        self.updatePlot()

    def clear_all_features(self):
        records = self.featurePointStore.all_records()
        if not records:
            return
        if any(record["source"] != "auto" for record in records):
            response = QMessageBox.question(
                self.iface.mainWindow(),
                "Peak / Valley Detection",
                "Clear all automatic, manual, and imported Peak/Valley points?",
                QMessageBox.Yes | QMessageBox.Cancel,
                QMessageBox.Cancel,
            )
            if response != QMessageBox.Yes:
                return
        self.featurePointStore.clear_all()
        self.updatePlot()

    def plot_x_to_profile_x(self, plot_x, profile_index, norm_factors):
        if self.is_normalized_by_segment():
            return self.ppc.plotX_to_profileX(plot_x, profile_index)
        factor = norm_factors[profile_index] if profile_index < len(norm_factors) else 1
        return plot_x / factor if factor else plot_x

    def profile_x_to_plot_x(self, profile_x, profile_index):
        if self.is_normalized_by_segment():
            return self.ppc.profileX_to_plotX(profile_x, profile_index)
        if self.dock.Grp_Normalized.isChecked():
            denominator = self.dpTool.sumD(self.pLines[profile_index])
            if denominator:
                return profile_x * self.dpTool.sumD(self.pLines[0]) / denominator
        return profile_x

    def handle_feature_plot_click(self, event, norm_factors):
        button = getattr(event.button, "value", event.button)
        if event.inaxes is None or event.xdata is None or button != 1:
            return
        context = self.current_peak_context(show_message=True)
        if context is None:
            return
        profile_x = self.plot_x_to_profile_x(event.xdata, context["profile_index"], norm_factors)
        if self.dock.Btn_PickDetectionRange.isChecked():
            self.handle_detection_range_plot_click(profile_x)
            return
        if self.dock.Btn_ModeSelect.isChecked():
            return
        nearest_index = min(
            range(len(context["x"])),
            key=lambda index: abs(context["x"][index] - profile_x),
        )
        tolerance = self.dock.Spn_SnapRange.value()
        if self.dock.Btn_ModeDelete.isChecked():
            self.featurePointStore.delete_nearest(
                context["profile_index"], context["raster_layer_id"], nearest_index, tolerance
            )
            self.updatePlot()
            return

        if self.dock.Btn_ModeAddPeak.isChecked():
            kind = "peak"
            sample_index = self.peakDetectionTool.snap_peak(context["y"], nearest_index, tolerance)
        elif self.dock.Btn_ModeAddValley.isChecked():
            kind = "valley"
            sample_index = self.peakDetectionTool.snap_valley(context["y"], nearest_index, tolerance)
        else:
            return
        if sample_index is None:
            return
        self.featurePointStore.add_manual(
            {
                "kind": kind,
                "profile_index": context["profile_index"],
                "raster_layer_id": context["raster_layer_id"],
                "sample_index": sample_index,
                "distance": context["x"][sample_index],
                "value": context["y"][sample_index],
                "point": context["centers"][sample_index],
                "prominence": None,
                "width": None,
                "data_label": context["data_label"],
            }
        )
        self.updatePlot()

    def create_feature_point_layer(self):
        records = self.featurePointStore.all_records()
        if not records:
            QMessageBox.information(self.iface.mainWindow(), "Peak / Valley Detection", "There are no points to export.")
            return
        base_name = "Line Profile Peaks Valleys"
        existing_names = {layer.name() for layer in QgsProject.instance().mapLayers().values()}
        layer_name = base_name
        suffix = 2
        while layer_name in existing_names:
            layer_name = "{} {}".format(base_name, suffix)
            suffix += 1
        crs = self.canvas.mapSettings().destinationCrs()
        uri = "Point?crs={}".format(crs.authid()) if crs.authid() else "Point"
        output_layer = QgsVectorLayer(uri, layer_name, "memory")
        provider = output_layer.dataProvider()
        fields = [
            QgsField("feature_id", QVariant.String),
            QgsField("type", QVariant.String),
            QgsField("source", QVariant.String),
            QgsField("profile", QVariant.Int),
            QgsField("data", QVariant.String),
            QgsField("raster_id", QVariant.String),
            QgsField("sample_idx", QVariant.Int),
            QgsField("distance", QVariant.Double),
            QgsField("value", QVariant.Double),
            QgsField("prominence", QVariant.Double),
            QgsField("width", QVariant.Double),
        ]
        provider.addAttributes(fields)
        output_layer.updateFields()
        features = []
        for record in records:
            point = record["point"]
            if not isinstance(point, QgsPointXY):
                point = QgsPointXY(*point)
            feature = QgsFeature()
            feature.setGeometry(QgsGeometry.fromPointXY(point))
            feature.setAttributes(
                [
                    record["id"],
                    record["kind"],
                    record["source"],
                    record["profile_index"] + 1,
                    record.get("data_label", ""),
                    record["raster_layer_id"],
                    record["sample_index"],
                    record["distance"],
                    record["value"],
                    record.get("prominence"),
                    record.get("width"),
                ]
            )
            features.append(feature)
        provider.addFeatures(features)
        output_layer.updateExtents()
        QgsProject.instance().addMapLayer(output_layer)
        QMessageBox.information(
            self.iface.mainWindow(),
            "Peak / Valley Detection",
            "Created point layer with {} features.".format(len(features)),
        )

    def export_feature_points(self, records, title):
        if not records:
            QMessageBox.information(self.iface.mainWindow(), "Peak / Valley Points", "There are no points to export.")
            return
        file_name, _ = QFileDialog.getSaveFileName(
            self.iface.mainWindow(),
            title,
            "peak_valley_points.csv",
            "CSV files (*.csv);;TSV files (*.tsv);;Text files (*.txt)",
        )
        if not file_name:
            return
        try:
            count = export_feature_point_file(file_name, records)
        except OSError as error:
            QMessageBox.warning(self.iface.mainWindow(), "Peak / Valley Points", str(error))
            return
        QMessageBox.information(
            self.iface.mainWindow(), "Peak / Valley Points", "Exported {} point(s).".format(count)
        )

    def export_current_feature_points(self):
        self.export_feature_points(self.current_feature_records(), "Export Current Peak / Valley Points")

    def export_all_feature_points(self):
        self.export_feature_points(self.featurePointStore.all_records(), "Export All Peak / Valley Points")

    def import_feature_points(self):
        context = self.current_peak_context(show_message=True)
        if context is None:
            return
        file_name, _ = QFileDialog.getOpenFileName(
            self.iface.mainWindow(),
            "Import Peak / Valley Points",
            "",
            "Point files (*.csv *.tsv *.txt);;CSV files (*.csv);;TSV files (*.tsv);;Text files (*.txt)",
        )
        if not file_name:
            return
        try:
            headers, rows = read_delimited_rows(file_name)
        except (OSError, UnicodeError, ValueError, csv.Error) as error:
            QMessageBox.warning(self.iface.mainWindow(), "Peak / Valley Points", str(error))
            return
        if "distance_um" not in headers:
            QMessageBox.warning(
                self.iface.mainWindow(), "Peak / Valley Points", "The file must include a distance_um column."
            )
            return
        default_type = None
        if "type" not in headers:
            selected, accepted = QInputDialog.getItem(
                self.iface.mainWindow(),
                "Import Peak / Valley Points",
                "Default type for imported rows:",
                ("Peak", "Valley"),
                0,
                False,
            )
            if not accepted:
                return
            default_type = selected.lower()
        entries, skipped = parse_import_rows(rows, default_type)
        records, mapping_skipped = map_imported_points(
            entries,
            context["x"],
            context["y"],
            context["centers"],
            context["profile_index"],
            context["raster_layer_id"],
            context["data_label"],
        )
        for record in records:
            self.featurePointStore.add_imported(record)
        skipped = sorted(set(skipped + mapping_skipped))
        self.updatePlot()
        message = "Processed {} valid row(s).".format(len(records))
        if skipped:
            message += " Skipped row(s): {}.".format(", ".join(str(number) for number in skipped))
        QMessageBox.information(self.iface.mainWindow(), "Peak / Valley Points", message)

    def import_alignment_file(self):
        default_path = "~"
        align_file, _ = QFileDialog.getOpenFileName(
            self.iface.mainWindow(), "Select alignment file", default_path, "Alignment files (*.json)"
        )
        if not align_file:
            return
        try:
            with open(align_file, "r") as f:
                alignment = json.load(f)
            px_size = self.get_pixel_size(alignment)
        except (OSError, ValueError, TypeError, KeyError, IndexError, json.JSONDecodeError) as error:
            self.log_message("Alignment import failed: {}".format(error), Qgis.Critical)
            QMessageBox.warning(
                self.iface.mainWindow(),
                "Line Profile",
                "The alignment file is invalid or does not contain usable reference points.",
            )
            return
        self.dock.Spn_PixelSize.setValue(px_size)

    def get_distance(self, pt1, pt2):
        # pt1 = [x1, y1]
        # pt2 = [x2, y2]
        a = math.pow(pt2[0] - pt1[0], 2)
        b = math.pow(pt2[1] - pt1[1], 2)
        return math.sqrt(a + b)

    def get_pixel_size(self, alignment):
        if not isinstance(alignment, list) or not alignment:
            raise ValueError("Alignment data must be a non-empty list")

        if "scale" in alignment[0]:
            # old format
            # scale of the first set of reference points
            scale = float(alignment[0]["scale"])
            if scale == 0:
                raise ValueError("Alignment scale must be non-zero")
            px_size = 1 / scale
        else:
            # new version
            # average px_size with all combinations of ref points
            alignment_n = len(alignment)
            combs = combinations(range(alignment_n), 2)
            pxsize_list = []
            for c in combs:
                if alignment[c[0]]["used"] == 0 or alignment[c[1]]["used"] == 0:
                    continue
                stage_distance = self.get_distance(pt1=alignment[c[0]]["stage"][0], pt2=alignment[c[1]]["stage"][0])
                canvas_distance = self.get_distance(pt1=alignment[c[0]]["canvas"][0], pt2=alignment[c[1]]["canvas"][0])
                if canvas_distance == 0:
                    continue
                pxsize_list.append(stage_distance / canvas_distance)
            if not pxsize_list:
                raise ValueError("No usable alignment reference pairs")
            px_size = sum(pxsize_list) / len(pxsize_list)

        if not math.isfinite(px_size) or px_size <= 0:
            raise ValueError("Pixel size must be a positive finite number")
        return px_size

    def sanitizePath(self, path):
        path = os.path.expanduser(path)
        path = os.path.expandvars(path)
        return os.path.abspath(path)
